---
title: "intrarow_weed_biomass_2023"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Load libraries**

```{r message=FALSE, warning=FALSE}

#Set work directory
setwd("/Users/ey239/Github/IMT/rmarkdowns")

#Load packages 
library(tidyverse) ##install.packages("tidyverse")
library(knitr)
library(patchwork) ##install.packages("patchwork")
library(skimr)     ##install.packages("skimr")
library(readxl)
library(janitor) ##install.packages("janitor")

library(kableExtra) ##install.packages("kableExtra")
library(webshot) ##install.packages("webshot")
webshot::install_phantomjs()
library(viridis) ##install.packages("viridis")
library(lme4) ##install.packages("lme4")
library(lmerTest) ##install.packages("lmerTest")
library(emmeans) ##install.packages("emmeans")
library(rstatix) ##install.packages("rstatix")
#library(Matrix) ##install.packages("Matrix")
library(multcomp) ##install.packages("multcomp")
library(multcompView) ##install.packages("multcompView")
library(ggResidpanel) ##install.packages("ggResidpanel")
#library(car)
#library(TMB)  ##install.packages("TMB")
#library(glmmTMB)  ##install.packages("glmmTMB")
#library(DHARMa)  ##install.packages("DHARMa")

#Load Functions
MeanPlusSe<-function(x) mean(x)+plotrix::std.error(x)

find_logw0=function(x){c=trunc(log(min(x[x>0],na.rm=T)))
d=exp(c)
return(d)}
```

<br>

# **Load and Clean Data**
### **Load individual datasets**
```{r message=FALSE, warning=FALSE}


fh_raw_2023 <- read_excel("~/Github/IMT/raw-data/farmhub_raw_2023.xlsx")
kable(head(fh_raw_2023))

cu_raw_2023 <- read_excel("~/Github/IMT/raw-data/cornell_raw_2023.xlsx") |> 
   rename(WBM = TOTWBM, INTRAWBM = INTRABM, INTERWBM = INTERBM)
kable(head(cu_raw_2023))

#me_raw_2023 <- read_excel("~/Github/IMT/raw-data/maine_raw_2023.xlsx", 
                          #na = c("na")) # convert na to NA
#kable(head(me_raw_2023))

vt_raw_2023 <- read_excel("~/Github/IMT/raw-data/vermont_raw_2023.xlsx")
kable(head(vt_raw_2023))

wi_raw_2023 <- read_excel("~/Github/IMT/raw-data/wisconsin_raw_2023.xlsx")
kable(head(wi_raw_2023))

```
### **Combine all datasets and clean**
```{r}
# Main did not divided wbm into inter and intra row and so is excluded
#Standardaze column names, convert to factors, check for outliers of variable**
all_raw_2023 <- bind_rows(fh_raw_2023, cu_raw_2023, vt_raw_2023, wi_raw_2023)

#Standardaze column names, convert to factors, check for outliers of variable**
all_clean_2023 <- clean_names(all_raw_2023) |>  
  rename ('mowing'= trt,'weeds'= microplot) |> 
  mutate(across(c(mowing, block, plot, weeds, loc), as.factor)) #|> 
  #mutate(is_outlier = intrawbm < (quantile(intrawbm, 0.25) - 1.5 * IQR(intrawbm)) |
                       #intrawbm > (quantile(intrawbm, 0.75) + 1.5 * IQR(intrawbm)))

#select and convert data for wbm analysis
  
all_intrawbm_clean_2023 <-all_clean_2023 |>              
  #filter(is_outlier == FALSE) |>              # Keep rows where beanyd is not an outlier
  filter(weeds %in% c("SW", "M")) |>       # Keep rows where SW and M are microplots
  mutate(intrawbm_grams_meter = (intrawbm * 2)) |> 
  mutate(intrawbm_kg_ha = ((intrawbm/0.5) *(10000))/(1000)) |>
  mutate(intrawbm_lbs_ac = (((intrawbm/0.5) *(10000))/(1000))* 0.892179)
kable(head(all_intrawbm_clean_2023)) 

```
<br>

# **Assumptions**

## **Levene's test**
```{r}
levene_test((intrawbm_kg_ha) ~ loc, data = all_intrawbm_clean_2023)
```
# **Model Testing**

### **location random**

```{r message=FALSE, warning=FALSE}
#data should be log transformed due to zeroes

all_intrawbm_random_2023 <- lmer(intrawbm_kg_ha ~  mowing*weeds + (1|loc) + (1|loc:block)+  (1|loc:block:mowing)  , data = all_intrawbm_clean_2023)

resid_panel(all_intrawbm_random_2023)

log_all_intrawbm_random_2023  <- lmer(log(intrawbm_kg_ha+1) ~  mowing*weeds + (1|loc) + (1|loc:block)+  (1|loc:block:mowing)  , data = all_intrawbm_clean_2023)

resid_panel(log_all_intrawbm_random_2023)

```

### **location fixed**

```{r}
all_intrawbm_fixed_2023 <- lmer(intrawbm_kg_ha ~ loc*mowing*weeds + (1|loc:block)+  (1|loc:block:mowing), data = all_intrawbm_clean_2023)

resid_panel(all_intrawbm_fixed_2023)

log_all_intrawbm_fixed_2023 <- lmer(log(intrawbm_kg_ha+1) ~ loc*mowing*weeds + (1|loc:block)+  (1|loc:block:mowing), data = all_intrawbm_clean_2023)

resid_panel(log_all_intrawbm_fixed_2023)
```
#**Anova
```{r}
 log_all_intrawbm_fixed_2023 |> 
  joint_tests() |> 
  kable()  
```
# **Interrow mowing has no effect on intrarow weed biomass**